ALTER TABLE apps ADD COLUMN long_description TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN app_store_url TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN developer TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN website_url TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN platform TEXT NOT NULL DEFAULT 'iOS';
