export interface Env { DB: D1Database; ASSETS?: R2Bucket; ADMIN_EMAIL?: string; ADMIN_API_KEY?: string }

const json = (data: unknown, init: ResponseInit = {}) => Response.json(data, { ...init, headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, X-Admin-Token', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', ...(init.headers || {}) } })

export default { async fetch(request: Request, env: Env): Promise<Response> {
  if (request.method === 'OPTIONS') return new Response(null, { headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, X-Admin-Token', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS' } })
  const url = new URL(request.url); if (!url.pathname.startsWith('/api/')) return new Response('screen.studio API')
  const assetMatch = url.pathname.match(/^\/api\/assets\/(.+)$/)
  if (assetMatch && request.method === 'GET' && env.ASSETS) { const object = await env.ASSETS.get(assetMatch[1]); if (!object) return new Response('Not found', { status: 404 }); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set('etag', object.httpEtag); headers.set('Cache-Control', 'public, max-age=31536000, immutable'); return new Response(object.body, { headers }) }
  const isWrite = request.method === 'POST' || request.method === 'PUT' || request.method === 'DELETE'
  if (isWrite && (!env.ADMIN_API_KEY || request.headers.get('X-Admin-Token') !== env.ADMIN_API_KEY)) return json({ error: 'Unauthorized' }, { status: 401 })
  if (url.pathname === '/api/assets' && request.method === 'POST' && env.ASSETS) { const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File)) return json({ error: 'file is required' }, { status: 400 }); const safeName = file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-'); const key = `uploads/${crypto.randomUUID()}-${safeName}`; await env.ASSETS.put(key, file.stream(), { httpMetadata: { contentType: file.type || 'application/octet-stream' } }); return json({ key, url: `/api/assets/${key}` }, { status: 201 }) }
  if (url.pathname === '/api/apps' && request.method === 'GET') { const { results } = await env.DB.prepare('SELECT * FROM apps ORDER BY created_at DESC').all(); return json(results) }
  if (url.pathname === '/api/apps' && request.method === 'POST') { const body = await request.json<any>(); const slug = body.slug || body.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); await env.DB.prepare('INSERT INTO apps (slug,name,category,description,icon,accent,long_description,app_store_url,developer,website_url,platform,screenshots) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,category=excluded.category,description=excluded.description,icon=excluded.icon,accent=excluded.accent,long_description=excluded.long_description,app_store_url=excluded.app_store_url,developer=excluded.developer,website_url=excluded.website_url,platform=excluded.platform,screenshots=excluded.screenshots,updated_at=CURRENT_TIMESTAMP').bind(slug,body.name,body.category,body.description || '',body.icon || '✦',body.accent || '#b8f25a',body.long_description || '',body.app_store_url || '',body.developer || '',body.website_url || '',body.platform || 'iOS',JSON.stringify(body.screenshots || [])).run(); return json({ slug }, { status: 201 }) }
  const match = url.pathname.match(/^\/api\/apps\/([^/]+)$/); if (match && request.method === 'PUT') { const body = await request.json<any>(); await env.DB.prepare('UPDATE apps SET name=?,category=?,description=?,icon=?,accent=?,long_description=?,app_store_url=?,developer=?,website_url=?,platform=?,screenshots=?,updated_at=CURRENT_TIMESTAMP WHERE slug=?').bind(body.name,body.category,body.description || '',body.icon || '✦',body.accent || '#b8f25a',body.long_description || '',body.app_store_url || '',body.developer || '',body.website_url || '',body.platform || 'iOS',JSON.stringify(body.screenshots || []),match[1]).run(); return json({ ok: true }) }
  if (match && request.method === 'DELETE') { await env.DB.prepare('DELETE FROM apps WHERE slug=?').bind(match[1]).run(); return json({ ok: true }) }
  return json({ error: 'Not found' }, { status: 404 })
} }
